/*******************************************************************************
* This file was generated by UI Builder.
* User should hand edit this file.
********************************************************************************/

#include "app_main.h"
#include "uib_views.h"
#include "uib_views_inc.h"
#include <curl/curl.h>

#define URL "http://192.168.0.143/"
#define ENDPOINT(tag) URL tag
#define callURL(tag) curlPOST(ENDPOINT(tag), "")

typedef struct _uib_view1_control_context {
 /* add your variables here */

} uib_view1_control_context;


static CURL *conn = NULL;
static bool curlPOST(char* endpoint, char* post)
{
    CURLcode code;

	curl_global_init(CURL_GLOBAL_ALL);

    conn = curl_easy_init();

    code = curl_easy_setopt(conn, CURLOPT_URL, endpoint);
	curl_easy_setopt(conn, CURLOPT_POSTFIELDS, post);

	curl_easy_perform(conn);

    curl_easy_cleanup(conn);
    curl_global_cleanup();

    return true;
}

void view1_button19_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("kapu-gyalog");
}

void view1_button21_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("kapu-auto");
}

void view1_button20_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("relay2-on");
}

void view1_button22_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("relay2-off");
}

void view1_button23_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("lampa-on");
}

void view1_button24_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("lampa-off");
}

void view1_button25_onclicked(uib_view1_view_context *vc, Evas_Object *obj, void *event_info) {
	callURL("wakeup");
}
